name: CI

on: [push]

jobs:
  build:
    name: Build

    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        node-version: [16

    runs-on: ${{ matrix.runs-on }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Semantic release
        run: yarn semantic-release
